/****** Object:  Database [PrCQRS_Files_DB]    Script Date: 14/09/2022 08:42:24 ******/
USE [master]
GO

CREATE DATABASE [PrCQRS_Files_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PrCQRS_Files_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PrCQRS_Files_DB.mdf' , SIZE = 512000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB ),
 FILEGROUP [FileStreamData] CONTAINS FILESTREAM  DEFAULT
( NAME = N'PrCQRS_Files_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PrCQRS_Files_Data' , MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'PrCQRS_Files_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PrCQRS_Files_DB_log.ldf' , SIZE = 512000KB , MAXSIZE = 2048GB , FILEGROWTH = 102400KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PrCQRS_Files_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PrCQRS_Files_DB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET RECOVERY FULL 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET  MULTI_USER 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PrCQRS_Files_DB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PrCQRS_Files_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PrCQRS_Files_DB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PrCQRS_Files_DB] SET  READ_WRITE 
GO


/****** Object:  Table [dbo].[FileStreamTable]    Script Date: 14/09/2022 08:34:39 ******/
USE [PrCQRS_Files_DB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FileStreamTable](
	[Id] [uniqueidentifier] ROWGUIDCOL NOT NULL,
	[Name] [nvarchar](250) NOT NULL,
	[Title] [nvarchar](4000) NULL,
	[Source] [nvarchar](4000) NULL,
	[Description] [nvarchar](4000) NULL,
	[InstituteId] [uniqueidentifier] NOT NULL,
	[ContentType] [nvarchar](500) NOT NULL,
	[DateCreated] [datetime] NOT NULL,
	[Data] [varbinary](max) FILESTREAM  NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY] FILESTREAM_ON [FileStreamData],
UNIQUE NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] FILESTREAM_ON [FileStreamData]
GO

ALTER TABLE [dbo].[FileStreamTable] ADD  DEFAULT (newid()) FOR [Id]
GO


