# Require https://github.com/madskristensen/RestClientVS
# ---------------------------------------------------------------
@hostname=localhost
@port=7001
@host=https://{{hostname}}:{{port}}
@contentType=application/json

## C R E A T E ###########################################
POST {{host}}/section/create
Content-Type: {{contentType}}

{
	
}
# TODO: add above the CreateSectionRequest values

##########################################################
# TODO: provide the Holding ID to GET, UPDATE and DELETE
@idToGet=00000000-0000-0000-0000-000000000000
@idToUpd=00000000-0000-0000-0000-000000000000
@idToDel=00000000-0000-0000-0000-000000000000

## G E T #################################################
GET {{host}}/section/get/id/{{idToGet}}
Content-Type: {{contentType}}

## U P D A T E ###########################################
PUT {{host}}/section/update
Content-Type: {{contentType}}

{
	"id": "{{idToUpd}}",

}
# TODO: add above the UpdateSectionRequest values

## D E L E T E ###########################################
DELETE {{host}}/section/delete/{{idToDel}}
Content-Type: {{contentType}}


